server:
  servlet:
    context-path: /api/v3

spring:
  application:
    name: payment-api
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

jwt:
  access-expiration-time: ${JWT_ACCESS_EXPIRATION_TIME}
  kiosk-expiration-time: ${JWT_KIOSK_EXPIRATION_TIME}
  prefix: ${JWT_PREFIX}
  header: ${JWT_HEADER}
  secret-key: ${JWT_SECRET_KEY}

van:
  api:
    terminals:
      1:
        host: ${VAN_API_HOST_1:}
        port: ${VAN_API_PORT_1:0}
      2:
        host: ${VAN_API_HOST_2:}
        port: ${VAN_API_PORT_2:0}
      3:
        host: ${VAN_API_HOST_3:}
        port: ${VAN_API_PORT_3:0}
      4:
        host: ${VAN_API_HOST_4:}
        port: ${VAN_API_PORT_4:0}
    protocol:
      stx: ${VAN_API_PROTOCOL_STX}
      etx: ${VAN_API_PROTOCOL_ETX}
      separator: ${VAN_API_PROTOCOL_SEPARATOR}
      record-separator: ${VAN_API_PROTOCOL_RECORD_SEPARATOR}
      blank: ${VAN_API_PROTOCOL_BLANK}
      ack: ${VAN_API_PROTOCOL_ACK}
      dle: ${VAN_API_PROTOCOL_DLE}
      form-feed: ${VAN_API_PROTOCOL_FORM_FEED}
      nak: ${VAN_API_PROTOCOL_NAK}
      transaction-timeout-seconds: ${VAN_API_PROTOCOL_TRANSACTION_TIMEOUT_SECONDS}
    message:
      payment-service-type: ${VAN_API_MESSAGE_PAYMENT_SERVICE_TYPE}
      refund-service-type: ${VAN_API_MESSAGE_REFUND_SERVICE_TYPE}
      terminal-close-service-type: ${VAN_API_MESSAGE_TERMINAL_CLOSE_SERVICE_TYPE}
      terminal-close-filler: ${VAN_API_MESSAGE_TERMINAL_CLOSE_FILLER}
      transaction-type: ${VAN_API_MESSAGE_TRANSACTION_TYPE}
      installment-months: ${VAN_API_MESSAGE_INSTALLMENT_MONTHS}
    codes:
      cancel-message-type: ${VAN_PROTOCOL_CODES_CANCEL_MESSAGE_TYPE}
      reject-status-prefix: ${VAN_PROTOCOL_CODES_REJECT_STATUS_PREFIX}
      card-insert-keyword: ${VAN_PROTOCOL_CODES_CARD_INSERT_KEYWORD}
member:
  read-api:
    url: ${MEMBER_API_URL:http://localhost:8081/api/v3}

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
  endpoints:
    web:
      exposure:
        include: health,prometheus
