plugins {
    id 'java-library'
}

dependencies {
    implementation project(':core:core-common')
    implementation project(':modules:web')
    implementation project(':domains:suggestion:suggestion-application')

    implementation 'org.springframework.boot:spring-boot-starter-web'

    testImplementation project(':domains:suggestion:suggestion-domain')
    testImplementation 'tools.jackson.core:jackson-databind'
    testImplementation 'tools.jackson.module:jackson-module-kotlin'
}
