plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.plugin.jpa'
}

dependencies {
    implementation project(':core:core-common')
    implementation project(':domains:investment:investment-domain')
    implementation project(':domains:investment:investment-application')

    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'tools.jackson.module:jackson-module-kotlin'
}
